package com.SuperheroSightings.springbootrestjdbctemplatemaven.modeldto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
/**
 * Represents a superhero or supervillain entity in the system.
 *
 * This class provides a data model for a Hero, including attributes such as name, description,
 * and superpower. It uses the Lombok library annotations to automatically generate getter
 * and setter methods, as well as no-args and all-args constructors.
 *
 * @author Mercy Aigbe Azeta
 * @version 1.0
 * @since 2023-09-11
 */
@NoArgsConstructor  // Lombok annotation to generate a no-args constructor.
@AllArgsConstructor // Lombok annotation to generate a constructor with arguments for all fields.
@Getter             // Lombok annotation to generate getters for all fields.
@Setter             // Lombok annotation to generate setters for all fields.
public class Hero {

    /**
     * Unique identifier for the hero. This is  generated by the database and used as the primary key.
     */
    private int id;

    /**
     * The name of the hero.
     */
    private String name;

    /**
     * A brief description of the hero.
     */
    private String description;

    /**
     * The superpower(s) that the hero possesses.
     */
    private String superpower;
}

