package com.SuperheroSightings.springbootrestjdbctemplatemaven.modeldto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
/**
 * Represents a geographical location where superhero sightings can occur.
 *
 * This class provides a data model for a Location, encapsulating attributes such as name,
 * description, address, latitude, and longitude. The Lombok library annotations are used
 * to automatically generate getter and setter methods, as well as no-args and all-args
 * constructors.
 *
 * @author Your Name (or the relevant author's name)
 * @version 1.0
 * @since 2023-09-11
 */
@NoArgsConstructor  // Lombok annotation to generate a no-args constructor.
@AllArgsConstructor // Lombok annotation to generate a constructor with arguments for all fields.
@Getter             // Lombok annotation to generate getters for all fields.
@Setter             // Lombok annotation to generate setters for all fields.
public class Location {

    /**
     * Unique identifier for the location. This is  generated by the database and used as the primary key.
     */
    private int id;

    /**
     * The name of the location.
     */
    private String name;

    /**
     * A description of the location.
     */
    private String description;

    /**
     * The physical address of the location. This could include the street name, city, state, and zip code.
     */
    private String address;

    /**
     * The latitude coordinate of the location.
     */
    private double latitude;

    /**
     * The longitude coordinate of the location.
     */
    private double longitude;
}
